stages:
  - build
  - deploy

variables:
  APP_DIR: /home/$DEPLOY_USER/node-react-docker
  DOCKER_COMPOSE_PATH: $APP_DIR/docker-compose.yml

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install -y openssh-client )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts

build:
  stage: build
  image: docker:24.0
  services:
    - docker:24.0-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t app-backend ./backend
    - docker build -t app-frontend ./frontend
    - echo "✅ Build complete"

deploy:
  stage: deploy
  script:
    - |
      ssh $DEPLOY_USER@$DEPLOY_HOST << 'EOF'
        set -e
        mkdir -p $APP_DIR
        if [ -d "$APP_DIR/.git" ]; then
          cd $APP_DIR && git pull
        else
          git clone $CI_REPOSITORY_URL $APP_DIR
        fi
        cd $APP_DIR
        docker compose down
        docker compose up --build -d
      EOF
